Test related articles
rockthejvm/rockthejvm-site pull request #207
Opened 2024-12-07 14:46 UTC by wkenned1

Fixes #206

2025-01-02 05:30 UTC, wkenned1 commented
- [ ] Use even sizing for related article cards (possibly with grid)
- [ ] Add check for article changes to prevent embedding the same content multiple times
- [ ] Migrate VectorDB to Cloudflare
- [ ] Move worker code into project

2025-01-02 20:24 UTC, andreilgeorgescu requested changes

2025-01-02 20:24 UTC, andreilgeorgescu commented on src/styles/base.css
> +  }
```suggestion
```

2025-01-02 20:24 UTC, andreilgeorgescu commented on src/styles/base.css
> +}
```suggestion
```

2025-01-26 02:30 UTC, andreilgeorgescu requested changes

2025-01-26 02:30 UTC, andreilgeorgescu commented on astro.config.mjs
> +}
Move to a file

2025-01-26 02:30 UTC, andreilgeorgescu commented on src/pages/articles/[slug].astro
> +    props: { article, articles },
```suggestion
    props: { article, relatedArticles },
```

2025-01-26 02:30 UTC, andreilgeorgescu commented on src/pages/articles/[slug].astro
> +const { article, articles } = Astro.props;
```suggestion
const { article, relatedArticles } = Astro.props;
```

2025-01-26 02:30 UTC, andreilgeorgescu commented on src/pages/articles/[slug].astro
> +  {articles}
```suggestion
  {relatedArticles}
```

2025-01-26 02:30 UTC, andreilgeorgescu commented on src/pages/articles/_layouts/ArticleLayout.astro
> +const { article, articles, headings, minutesRead } = Astro.props;
```suggestion
const { article, relatedArticles, headings, minutesRead } = Astro.props;
```

2025-01-26 02:30 UTC, andreilgeorgescu commented on src/pages/articles/_layouts/ArticleLayout.astro
> +  articles: CollectionEntry<"articles">[];
```suggestion
  relatedArticles: CollectionEntry<"articles">[];
```

2025-01-26 02:30 UTC, andreilgeorgescu commented on astro.config.mjs
> +  const regex = /## Conclusion\s+([\s\S]*?)(?=\n\n|$)/;
Ending logic here should consider multiple paragraphs or a new h2 (such as references)

2025-01-26 02:30 UTC, andreilgeorgescu commented on src/pages/articles/_layouts/ArticleLayout.astro
> +
Parse with zod

2025-01-26 02:30 UTC, andreilgeorgescu commented on tailwind.config.js
> +  darkMode: ["class"],
See what you actually need in this file

2025-01-27 22:15 UTC, closed without merging